<a href="https://colab.research.google.com/github/zwelisizwe/homework-0/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Get data

In [10]:
!wget https://storage.googleapis.com/bdt-beam/users_v.csv

--2023-09-19 18:08:02--  https://storage.googleapis.com/bdt-beam/users_v.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.101.207, 142.251.2.207, 74.125.137.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.101.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 143675 (140K) [text/csv]
Saving to: ‘users_v.csv.1’

users_v.csv.1       100%[===================>] 140.31K   468KB/s    in 0.3s

2023-09-19 18:08:03 (468 KB/s) - ‘users_v.csv.1’ saved [143675/143675]

Top 10 (Head)

In [11]:
!head -n 10 users_v.csv

user_id,name,gender,age,address,date_joined
1,Anthony Wolf,male,73,New Rachelburgh-VA-49583,2019/03/13
2,James Armstrong,male,56,North Jillianfort-UT-86454,2020/11/06
3,Cody Shaw,male,75,North Anne-SC-53799,2004/05/29
4,Sierra Hamilton,female,76,New Angelafurt-ME-46190,2005/08/26
5,Chase Davis,male,31,South Bethmouth-WI-18562,2018/04/30
6,Sierra Andrews,female,21,Ryanville-MI-69690,2007/05/25
7,Ann Stone,female,41,Smithmouth-SD-17340,2005/01/05
8,Karen Santos,female,34,Mariaville-AK-29888,2003/12/12
9,Ronald Meyer,male,41,North Cherylhaven-NJ-04197,2015/11/14

Number of Rows

In [12]:
!wc -l users_v.csv

2358 users_v.csv

Sample

In [22]:
#!head -n 1 users_v.csv > users_sample.csv  # Copy the header
!shuf -n 1000 users_v.csv | tail -n +2 >> users_sample.csv

Sort

In [21]:
!head -n 1 users_v.csv > sorted_users_sample.csv  # Copy the header
!sort -t ',' -k 1,1n users_sample.csv > sorted_users_sample.csv

Overwrite

In [17]:
!sort -t ',' -k 1 users_sample.csv -o users_sample.csv

Last ten lines (tail)

In [18]:
!tail -n 10 users_sample.csv

972,Laura Dominguez,female,35,New Codyberg-WV-02830,2011/06/02
973,Megan Kidd,female,25,Gravesport-AZ-94586,2005/09/14
978,Ralph Ball,male,71,Julianshire-WV-10729,2019/09/05
97,Robert Williams,male,26,Rachelmouth-SD-10847,2021/08/08
981,Joshua Mitchell,male,62,Maryport-OK-95214,2002/08/31
988,Marissa Cummings,female,37,Clarkberg-WY-29479,2003/12/27
990,Christopher Fox,male,69,West Samanthaberg-CA-56486,2001/11/28
998,Ms. Candice Sims DVM,female,24,Marychester-CT-22544,2005/02/18
9,Ronald Meyer,male,41,North Cherylhaven-NJ-04197,2015/11/14
user_id,name,gender,age,address,date_joined

Load to pandas

In [27]:
import pandas as pd

users = pd.read_csv('users_v.csv')
users

,user_id,name,gender,age,address,date_joined
0,1,Anthony Wolf,male,73,New Rachelburgh-VA-49583,2019/03/13
1,2,James Armstrong,male,56,North Jillianfort-UT-86454,2020/11/06
2,3,Cody Shaw,male,75,North Anne-SC-53799,2004/05/29
3,4,Sierra Hamilton,female,76,New Angelafurt-ME-46190,2005/08/26
4,5,Chase Davis,male,31,South Bethmouth-WI-18562,2018/04/30
...,...,...,...,...,...,...
2352,2353,Brittney Graham,female,40,Brownland-CO-71229,2005/07/10
2353,2354,Allison Schmidt,female,43,Port Logan-MD-38588,2008/11/30
2354,2355,Christopher Johnson,male,68,North Justinton-VA-32798,2006/08/01
2355,2356,Mark Brown,male,67,New Kayleefurt-MA-82581,2013/11/16
2356,2357,Steven Robinson,male,45,Mistytown-HI-31737,2015/03/21

In [52]:
users.head(10)

,user_id,name,gender,age,address,date_joined,surname
0,1,Anthony Wolf,male,73,New Rachelburgh-VA-49583,2019/03/13,Wolf
1,2,James Armstrong,male,56,North Jillianfort-UT-86454,2020/11/06,Armstrong
2,3,Cody Shaw,male,75,North Anne-SC-53799,2004/05/29,Shaw
3,4,Sierra Hamilton,female,76,New Angelafurt-ME-46190,2005/08/26,Hamilton
4,5,Chase Davis,male,31,South Bethmouth-WI-18562,2018/04/30,Davis
5,6,Sierra Andrews,female,21,Ryanville-MI-69690,2007/05/25,Andrews
6,7,Ann Stone,female,41,Smithmouth-SD-17340,2005/01/05,Stone
7,8,Karen Santos,female,34,Mariaville-AK-29888,2003/12/12,Santos
8,9,Ronald Meyer,male,41,North Cherylhaven-NJ-04197,2015/11/14,Meyer
9,10,Steven Rivera,male,43,Wayneside-VT-29040,2003/05/15,Rivera

In [29]:
print(users['age'].max() , users['age'].min())

80 18

In [32]:
users['age'].describe()

count    2357.000000
mean       49.054731
std        18.206348
min        18.000000
25%        33.000000
50%        49.000000
75%        65.000000
max        80.000000
Name: age, dtype: float64

In [51]:
 users['surname'] = users['name'].str.split(' ').str[-1]

In [54]:
users.tail(10)

,user_id,name,gender,age,address,date_joined,surname
2347,2348,Victoria Edwards,female,68,Lake Jamesberg-NY-88824,2001/09/03,Edwards
2348,2349,Chris Ellis,male,46,Port Richardside-NY-77994,2011/03/18,Ellis
2349,2350,Kimberly Smith,female,19,East Anthony-GA-00646,2021/06/20,Smith
2350,2351,William Nelson,male,67,Lake Parkerside-MN-06905,2005/12/21,Nelson
2351,2352,Nancy Clark,female,80,Jamesshire-AK-88437,2001/12/12,Clark
2352,2353,Brittney Graham,female,40,Brownland-CO-71229,2005/07/10,Graham
2353,2354,Allison Schmidt,female,43,Port Logan-MD-38588,2008/11/30,Schmidt
2354,2355,Christopher Johnson,male,68,North Justinton-VA-32798,2006/08/01,Johnson
2355,2356,Mark Brown,male,67,New Kayleefurt-MA-82581,2013/11/16,Brown
2356,2357,Steven Robinson,male,45,Mistytown-HI-31737,2015/03/21,Robinson

In [56]:
users['date_joined'] = pd.to_datetime(users['date_joined'])